### ISSUE TITLE
Translate this game to C

### ISSUE THREAD

**Issue by AnatoliyLl** [SpringTech-Studios/SisijaFight#17]
C is faster than C++ and C++ is a bit, um... bloat...
You can use short int instead of bool, you can make `#define true 1` and `#define false 0`, if you want bool, just `typedef short bool`, you can use structs instead of classes(because i think classes are sh*t), you can even just use functions

**Comment by Lulu-Games** [comment]
Are there Lambdas in C?

**Comment by Lulu-Games** [comment]
I need the classes and pointers

**Comment by Lulu-Games** [comment]
The system requirements are high so there will not be any difference

**Comment by AnatoliyLl** [comment]
Oh, C is for low-level, maybe, C++ will be good here
