### ISSUE TITLE
Port this game to Andesaurux

### ISSUE THREAD

**Issue by Anatoliy6463** [SpringTech-Studios/SisijaFight#2]
I think, this game must be ported to Andesaurux

**Comment by Lulu-Games** [comment]
🤣 do you have any  Compiler collections for that?

**Comment by Lulu-Games** [comment]
Do you want to program things for SisijaFight?

**Comment by Anatoliy6463** [comment]
Yes

**Comment by Anatoliy6463** [comment]
> 🤣 do you have any Compiler collections for that?

GNU Compiler Collection, my kernel will be POSIX-compatible and most Unix-programs will be compatible with my kernel

**Comment by Anatoliy6463** [comment]
I moved /include to /usr, to make it compatible with GCC

**Comment by Lulu-Games** [comment]
Can you port it to andesaurux? I don't have time for that

**Comment by Anatoliy6463** [comment]
> Can you port it to andesaurux? I don't have time for that

Yes

**Comment by Lulu-Games** [comment]
Good
