### ISSUE TITLE
...

### ISSUE THREAD

**Issue by AnatoliyL2** [SpringTech-Studios/SisijaFight#21]
@Lulu-Games pls add me to SpringTech or at least make me collaborator.
This f*cking toxic mintsuki and his friends blocked me again.

**Comment by AnatoliyL2** [comment]
Do you hate him? If yes, i can add you to antiliminers

**Comment by AnatoliyL2** [comment]
@Lulu-Games can you help me with evogalaxy? I need game engine and physical engine

**Comment by Lulu-Games** [comment]
Why do you need? We could make one based on Irrlicht, Bullet, OpenAL, AngelScript, PugiXML, Dear IMGUI and Wrappers to connect them

**Comment by Lulu-Games** [comment]
In your shoes I would Appologize the developers who banned you 2 Times. But mention that you will not ever be CALLED A CHILD! I think the antilimimers discussion will only lead to another bann...

**Comment by AnatoliyL2** [comment]
> In your shoes I would Appologize the developers who banned you 2 Times. But mention that you will not ever be CALLED A CHILD! I think the antilimimers discussion will only lead to another bann...

No, i was banned because i called him 'F*cking idiot'

**Comment by AnatoliyL2** [comment]
F*ck limine(made by mintsuki that banned me) is in all hobby operating systems(thank god OS that i recenttly wanted to contribute to has version with GRUB)

**Comment by Lulu-Games** [comment]
> > In your shoes I would Appologize the developers who banned you 2 Times. But mention that you will not ever be CALLED A CHILD! I think the antilimimers discussion will only lead to another bann...
> 
> No, i was banned because i called him 'F*cking idiot'

Yes I know. But you did because you was called a child! So apologizing would help you to get out of this situation.

**Comment by Lulu-Games** [comment]
Just copy the SGE-unit of SisijaFight. There are wrappers for the GUI-elements, Angelscript... And copy the libs.
